In [1]:
import pandas as pd

path = r'/home/iagojorcovix/projeto_medcare_curitiba/data_raw/2025-06-06_Sistema_E-Saude_Medicos_-_Base_de_Dados.csv'

df = pd.read_csv(
    path,
    encoding='latin1',
    sep=';'
)

df.head()

/tmp/ipykernel_11583/2925851600.py:5: DtypeWarning: Columns (0: Código do CBO) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,Data do Atendimento,Data de Nascimento,Sexo,Código do Tipo de Unidade,Tipo de Unidade,Código da Unidade,Descrição da Unidade,Código do Procedimento,Descrição do Procedimento,Código do CBO,...,Grupo Comunitário,Meio de Comunicacao,Meio de Transporte,Municício,Bairro,Nacionalidade,cod_usuario,origem_usuario,residente,cod_profissional
0,01/02/2025 00:10:45,06/10/1993 00:00:00,M,2,UPA,9214097,UPA TATUQUARA,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,NAO PARTICIPA,"TELEVISAO,RADIO","ONIBUS,CARRO",CURITIBA,TATUQUARA,Estrangeiro,12099862,1,1,128347
1,01/02/2025 00:20:05,19/12/1997 00:00:00,F,2,UPA,3827836,UPA PINHEIRINHO,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,NAO PARTICIPA,"TELEVISAO,RADIO,OUTROS","OUTROS,ONIBUS,CARRO",CURITIBA,PINHEIRINHO,Brasileira,182635,1,1,127612
2,01/02/2025 00:25:08,06/10/1990 00:00:00,F,2,UPA,5323436,UPA CAJURU,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,NAO PARTICIPA,RADIO,ONIBUS,CURITIBA,CAJURU,Brasileira,2484209,1,1,116606
3,01/02/2025 00:11:35,13/10/1976 00:00:00,M,2,UPA,9214097,UPA TATUQUARA,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,OUTROS,"TELEVISAO,RADIO,OUTROS","ONIBUS,CARRO",CURITIBA,CAMPO DE SANTANA,Brasileira,3536128,1,1,97106
4,01/02/2025 00:29:48,03/09/2001 00:00:00,F,2,UPA,5323495,UPA CIDADE INDUSTRIAL,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,NAO PARTICIPA,"TELEVISAO,RADIO,OUTROS","ONIBUS,CARRO",CURITIBA,NOVO MUNDO,Brasileira,9886667,1,1,115423

In [2]:
df.shape

(1218394, 42)

In [3]:
nulls = pd.DataFrame({
    'qtd_null': df.isna().sum(),
    'pct_null': df.isna().mean() * 100
})

nulls.sort_values('pct_null', ascending=False)

                                              qtd_null   pct_null
Data do Internamento                           1213946  99.634929
Estabelecimento Destino                        1213625  99.608583
CID do Internamento                            1213625  99.608583
Estabelecimento Solicitante                    1213625  99.608583
Área de Atuação                                1093136  89.719418
Grupo Comunitário                               248626  20.406043
Fezes/Urina                                     245805  20.174508
Meio de Comunicacao                             244382  20.057715
Meio de Transporte                              243993  20.025788
Abastecimento                                   243930  20.020617
Destino Lixo                                    243562  19.990414
Em Caso de Doença                               242656  19.916053
Tipo de Habitação                               241814  19.846946
Tratamento no Domicílio                         240684  19.754201
Cômodos                                          54236   4.451434
Código do CID                                      299   0.024541
Descrição do CID                                   299   0.024541
Descrição do Procedimento                            0   0.000000
Data de Nascimento                                   0   0.000000
Data do Atendimento                                  0   0.000000
Código do Procedimento                               0   0.000000
Descrição da Unidade                                 0   0.000000
Código da Unidade                                    0   0.000000
Tipo de Unidade                                      0   0.000000
Código do Tipo de Unidade                            0   0.000000
Sexo                                                 0   0.000000
Código do CBO                                        0   0.000000
Desencadeou Internamento                             0   0.000000
Descrição do CBO                                     0   0.000000
Qtde Dispensada Farmácia Curitibana                  0   0.000000
Qtde Prescrita Farmácia Curitibana                   0   0.000000
Encaminhamento para Atendimento Especialista         0   0.000000
Qtde de Medicamento Não Padronizado                  0   0.000000
Solicitação de Exames                                0   0.000000
Energia Elétrica                                     0   0.000000
Municício                                            0   0.000000
Bairro                                               0   0.000000
Nacionalidade                                        0   0.000000
cod_usuario                                          0   0.000000
origem_usuario                                       0   0.000000
residente                                            0   0.000000
cod_profissional                                     0   0.000000

In [4]:
df_clean = df.drop(columns = ['Data do Internamento','Estabelecimento Destino','CID do Internamento','Estabelecimento Solicitante','Área de Atuação']).copy()

In [5]:
nulls = pd.DataFrame({
    'qtd_null': df_clean.isna().sum(),
    'pct_null': df_clean.isna().mean() * 100
})

nulls.sort_values('pct_null', ascending=False)

                                              qtd_null   pct_null
Grupo Comunitário                               248626  20.406043
Fezes/Urina                                     245805  20.174508
Meio de Comunicacao                             244382  20.057715
Meio de Transporte                              243993  20.025788
Abastecimento                                   243930  20.020617
Destino Lixo                                    243562  19.990414
Em Caso de Doença                               242656  19.916053
Tipo de Habitação                               241814  19.846946
Tratamento no Domicílio                         240684  19.754201
Cômodos                                          54236   4.451434
Código do CID                                      299   0.024541
Descrição do CID                                   299   0.024541
Data do Atendimento                                  0   0.000000
Tipo de Unidade                                      0   0.000000
Código do Tipo de Unidade                            0   0.000000
Sexo                                                 0   0.000000
Data de Nascimento                                   0   0.000000
Descrição do Procedimento                            0   0.000000
Código do Procedimento                               0   0.000000
Código da Unidade                                    0   0.000000
Descrição da Unidade                                 0   0.000000
Encaminhamento para Atendimento Especialista         0   0.000000
Desencadeou Internamento                             0   0.000000
Qtde Dispensada Farmácia Curitibana                  0   0.000000
Qtde de Medicamento Não Padronizado                  0   0.000000
Qtde Prescrita Farmácia Curitibana                   0   0.000000
Solicitação de Exames                                0   0.000000
Descrição do CBO                                     0   0.000000
Código do CBO                                        0   0.000000
Energia Elétrica                                     0   0.000000
Municício                                            0   0.000000
Bairro                                               0   0.000000
Nacionalidade                                        0   0.000000
cod_usuario                                          0   0.000000
origem_usuario                                       0   0.000000
residente                                            0   0.000000
cod_profissional                                     0   0.000000

In [6]:
df_clean['Descrição do CBO'].value_counts()

Descrição do CBO
MEDICO CLINICO                                   440957
MEDICO GENERALISTA                               289535
MEDICO DA ESTRATEGIA DE SAUDE DA FAMILIA         229405
MEDICO DE FAMILIA E COMUNIDADE                   146581
MEDICO PEDIATRA                                   58744
MEDICO GINECOLOGISTA E OBSTETRA                   28171
MEDICO NEUROLOGISTA                                5665
MEDICO PSIQUIATRA                                  2184
MEDICO GERIATRA                                    2129
MEDICO ENDOCRINOLOGISTA E METABOLOGISTA            2038
MEDICO UROLOGISTA                                  2016
MEDICO DERMATOLOGIA                                1790
MEDICO CARDIOLOGISTA                               1518
MEDICO OFTALMOLOGISTA                              1344
MEDICO CIRURGIAO GERAL                             1313
MEDICO COLOPROCTOLOGISTA                           1300
MEDICO ACUPUNTURISTA                               1006
MEDICO MASTOLOGISTA                                 568
MEDICO GASTROENTEROLOGISTA                          459
MEDICO ANESTESIOLOGISTA                             441
MEDICO PNEUMOLOGISTA                                412
MEDICO INFECTOLOGISTA                               269
MEDICO EM RADIOLOGIA E DIAGNOSTICO POR IMAGEM       198
MEDICO HOMEOPATA                                    123
MEDICO EM CIRURGIA VASCULAR                         101
MEDICO CIRURGIAO TORACICO                            90
MEDICO RESIDENTE                                     37
Name: count, dtype: int64

In [7]:
df_clean.head().iloc[:, :15]

,Data do Atendimento,Data de Nascimento,Sexo,Código do Tipo de Unidade,Tipo de Unidade,Código da Unidade,Descrição da Unidade,Código do Procedimento,Descrição do Procedimento,Código do CBO,Descrição do CBO,Código do CID,Descrição do CID,Solicitação de Exames,Qtde Prescrita Farmácia Curitibana
0,01/02/2025 00:10:45,06/10/1993 00:00:00,M,2,UPA,9214097,UPA TATUQUARA,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,MEDICO CLINICO,S936,ENTORSE E DISTENSAO DE OUTRAS PARTES E DE PART...,Nao,25
1,01/02/2025 00:20:05,19/12/1997 00:00:00,F,2,UPA,3827836,UPA PINHEIRINHO,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,MEDICO CLINICO,N23,COLICA NEFRETICA NAO ESPECIFICADA,Sim,86
2,01/02/2025 00:25:08,06/10/1990 00:00:00,F,2,UPA,5323436,UPA CAJURU,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,MEDICO CLINICO,G43,ENXAQUECA,Sim,21
3,01/02/2025 00:11:35,13/10/1976 00:00:00,M,2,UPA,9214097,UPA TATUQUARA,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,MEDICO CLINICO,B01,VARICELA,Nao,0
4,01/02/2025 00:29:48,03/09/2001 00:00:00,F,2,UPA,5323495,UPA CIDADE INDUSTRIAL,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,MEDICO CLINICO,M752,TENDINITE BICEPITAL,Sim,124

In [8]:
df_clean.head().iloc[:, 15:30]

,Qtde Dispensada Farmácia Curitibana,Qtde de Medicamento Não Padronizado,Encaminhamento para Atendimento Especialista,Desencadeou Internamento,Tratamento no Domicílio,Abastecimento,Energia Elétrica,Tipo de Habitação,Destino Lixo,Fezes/Urina,Cômodos,Em Caso de Doença,Grupo Comunitário,Meio de Comunicacao,Meio de Transporte
0,20,1,Nao,Nao,SEM TRATAMENTO,REDE PÚBLICA,Nao,TIJOLO/ALVENARIA COM REVESTIMENTO,COLETADO,SISTEMA DE ESGOTO,6.0,"UNIDADE DE SAUDE,HOSPITAL",NAO PARTICIPA,"TELEVISAO,RADIO","ONIBUS,CARRO"
1,60,51,Nao,Sim,SEM TRATAMENTO,REDE PÚBLICA,Sim,TIJOLO/ALVENARIA COM REVESTIMENTO,COLETADO,SISTEMA DE ESGOTO,5.0,"HOSPITAL,UNIDADE DE SAUDE",NAO PARTICIPA,"TELEVISAO,RADIO,OUTROS","OUTROS,ONIBUS,CARRO"
2,21,0,Nao,Nao,SEM TRATAMENTO,OUTROS,Sim,OUTRO MATERIAL,CÉU ABERTO,CÉU ABERTO,2.0,UNIDADE DE SAUDE,NAO PARTICIPA,RADIO,ONIBUS
3,0,0,Nao,Nao,CLORACAO,REDE PÚBLICA,Sim,TIJOLO/ALVENARIA COM REVESTIMENTO,COLETADO,SISTEMA DE ESGOTO,4.0,UNIDADE DE SAUDE,OUTROS,"TELEVISAO,RADIO,OUTROS","ONIBUS,CARRO"
4,80,20,Nao,Nao,FILTRACAO,REDE PÚBLICA,Sim,TIJOLO/ALVENARIA COM REVESTIMENTO,COLETADO,SISTEMA DE ESGOTO,4.0,"FARMACIA,UNIDADE DE SAUDE,HOSPITAL",NAO PARTICIPA,"TELEVISAO,RADIO,OUTROS","ONIBUS,CARRO"

In [9]:
df_clean.head().iloc[:, 30:]

,Municício,Bairro,Nacionalidade,cod_usuario,origem_usuario,residente,cod_profissional
0,CURITIBA,TATUQUARA,Estrangeiro,12099862,1,1,128347
1,CURITIBA,PINHEIRINHO,Brasileira,182635,1,1,127612
2,CURITIBA,CAJURU,Brasileira,2484209,1,1,116606
3,CURITIBA,CAMPO DE SANTANA,Brasileira,3536128,1,1,97106
4,CURITIBA,NOVO MUNDO,Brasileira,9886667,1,1,115423

In [10]:
df_clean['Descrição da Unidade'].nunique()

125

In [11]:
df_clean['Código do CID'].str.strip().str[:3].nunique()

1630

In [12]:
df_clean['Grupo Comunitário'].value_counts()

Grupo Comunitário
NAO PARTICIPA      677610
OUTROS             187456
GRUPO RELIGIOSO     69002
COOPERATIVA         27992
ASSOCIACAO           7708
Name: count, dtype: int64

In [13]:
df_clean['cd_CID_resumido'] = df_clean['Código do CID'].str.strip().str[:3]

In [14]:
#Clusterizar paciêntes para enteder melhor o perfil dos pacientes que estão sendo atendidos no sistema de saúde.

columns_cluster_paciente = [
    'Sexo','cd_CID_resumido','Energia Elétrica','Tipo de Habitação','Destino Lixo', 'Fezes/Urina', 'Cômodos','Em Caso de Doença','Meio de Comunicacao','Meio de Transporte','Tratamento no Domicílio'
]

df_cluster_paciente = df_clean[columns_cluster_paciente]

In [15]:
print(df_cluster_paciente.shape)

print(df_cluster_paciente.dropna().shape)

(1218394, 11)
(962862, 11)

In [16]:
X = df_cluster_paciente.dropna()

In [17]:
X.head()

,Sexo,cd_CID_resumido,Energia Elétrica,Tipo de Habitação,Destino Lixo,Fezes/Urina,Cômodos,Em Caso de Doença,Meio de Comunicacao,Meio de Transporte,Tratamento no Domicílio
0,M,S93,Nao,TIJOLO/ALVENARIA COM REVESTIMENTO,COLETADO,SISTEMA DE ESGOTO,6.0,"UNIDADE DE SAUDE,HOSPITAL","TELEVISAO,RADIO","ONIBUS,CARRO",SEM TRATAMENTO
1,F,N23,Sim,TIJOLO/ALVENARIA COM REVESTIMENTO,COLETADO,SISTEMA DE ESGOTO,5.0,"HOSPITAL,UNIDADE DE SAUDE","TELEVISAO,RADIO,OUTROS","OUTROS,ONIBUS,CARRO",SEM TRATAMENTO
2,F,G43,Sim,OUTRO MATERIAL,CÉU ABERTO,CÉU ABERTO,2.0,UNIDADE DE SAUDE,RADIO,ONIBUS,SEM TRATAMENTO
3,M,B01,Sim,TIJOLO/ALVENARIA COM REVESTIMENTO,COLETADO,SISTEMA DE ESGOTO,4.0,UNIDADE DE SAUDE,"TELEVISAO,RADIO,OUTROS","ONIBUS,CARRO",CLORACAO
4,F,M75,Sim,TIJOLO/ALVENARIA COM REVESTIMENTO,COLETADO,SISTEMA DE ESGOTO,4.0,"FARMACIA,UNIDADE DE SAUDE,HOSPITAL","TELEVISAO,RADIO,OUTROS","ONIBUS,CARRO",FILTRACAO

In [18]:
X.describe()

             Cômodos
count  962862.000000
mean        5.351564
std        11.636669
min        -6.000000
25%         5.000000
50%         5.000000
75%         6.000000
max      5997.000000

In [19]:
import pandas as pd
import numpy as np

cid = (
    X['cd_CID_resumido']
    .astype('string')
    .str.strip()
    .str.upper()
)

letra = cid.str[0]

numero = pd.to_numeric(
    cid.str.slice(1, 3),
    errors='coerce'
)

condicoes = [
    letra.isin(['A', 'B']),
    (letra == 'C') | ((letra == 'D') & (numero <= 48)),
    (letra == 'D') & (numero >= 50),
    letra == 'E',
    letra == 'F',
    letra == 'G',
    (letra == 'H') & (numero <= 59),
    (letra == 'H') & (numero >= 60),
    letra == 'I',
    letra == 'J',
    letra == 'K',
    letra == 'L',
    letra == 'M',
    letra == 'N',
    letra == 'O',
    letra == 'P',
    letra == 'Q',
    letra == 'R',
    letra.isin(['S', 'T']),
    letra.isin(['V', 'W', 'X', 'Y']),
    letra == 'Z',
    letra == 'U'
]

capitulos = np.arange(1, 23)

X['grupo_cid'] = np.select(
    condicoes,
    capitulos,
    default=0
).astype(np.int8)

In [21]:
X = X.drop(columns=['cd_CID_resumido'])

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.cluster import KMeans

colunas_numericas = ['Cômodos']


colunas_categoricas = X.drop(columns=colunas_numericas).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            colunas_numericas
        ),
        (
            'cat',
            OneHotEncoder(
                handle_unknown='ignore',
                sparse_output=True
            ),
            colunas_categoricas
        )
    ]
)

X_processed = preprocessor.fit_transform(X)